title: Parabólica
email: parabolica.studio@gmail.com
description: >
  Coletivo de design brasiliense
baseurl: ""
url: "http://parabolica.design"
permalink: pretty
assets: "/assets" 
markdown: kramdown
sass:
  style: compressed
grid: 24
